fail-on-severity: 'low'
allow-licenses:
  - 'BSD-2-Clause'
  - 'BSD-3-Clause'
  - 'MIT'
  - 'Apache-2.0'
  - 'ISC'
  - 'BlueOak-1.0.0'
  - '0BSD'
  - 'Python-2.0'
  - 'LicenseRef-scancode-secret-labs-2011 AND MIT-CMU'  # Pillow's license
fail-on-scopes:
  - 'runtime'
  - 'development'
  - 'unknown'
license-check: true
vulnerability-check: true
